spark.app.name : SparkDataSync
spark.master : local[2]
spark.sql.shuffle.partitions : 500
spark.jars : "/path/SparkDataSync/lib/postgresql-42.6.0.jar"
spark.driver.extraClassPath : "/path/SparkDataSync/lib/postgresql-42.6.0.jar"
spark.executor.extraClassPath : "/path/SparkDataSync/lib/postgresql-42.6.0.jar"
spark.jars.packages : "org.postgresql:postgresql:42.6.0"